In [1]:
import numpy as np
a = {'acc' : (lambda y, t: (y.argmax(-1)==t.argmax(-1)).mean())(np.array([1,2,3]),np.array([1,2,5]))}
a


{'acc': 1.0}

In [2]:
b = np.array([1,2,55,4,7,4,3])
b.argmax()

2

In [3]:
params = dict(
learning_rate = 9e-4,
num_epochs = 100,
stats_interval = 1,
input_dim = 784, 
output_dim = 47,
hidden_dim = [32, 64, 128])
params['learning_rate']

0.0009

In [4]:
import numpy as np
input = np.arange(48).reshape(4,3,2,2)
print(input)
mask = ((np.random.rand(input.shape[1])>0.5)*1)[:,None,None]
print(mask)
input * mask


[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]

  [[ 8  9]
   [10 11]]]


 [[[12 13]
   [14 15]]

  [[16 17]
   [18 19]]

  [[20 21]
   [22 23]]]


 [[[24 25]
   [26 27]]

  [[28 29]
   [30 31]]

  [[32 33]
   [34 35]]]


 [[[36 37]
   [38 39]]

  [[40 41]
   [42 43]]

  [[44 45]
   [46 47]]]]
[[[1]]

 [[0]]

 [[0]]]


array([[[[ 0,  1],
         [ 2,  3]],

        [[ 0,  0],
         [ 0,  0]],

        [[ 0,  0],
         [ 0,  0]]],


       [[[12, 13],
         [14, 15]],

        [[ 0,  0],
         [ 0,  0]],

        [[ 0,  0],
         [ 0,  0]]],


       [[[24, 25],
         [26, 27]],

        [[ 0,  0],
         [ 0,  0]],

        [[ 0,  0],
         [ 0,  0]]],


       [[[36, 37],
         [38, 39]],

        [[ 0,  0],
         [ 0,  0]],

        [[ 0,  0],
         [ 0,  0]]]])

In [24]:
import os
correct_outputs = np.load(os.path.join(os.environ['MLP_DATA_DIR'], 'regularization_debug_pack.npy'), allow_pickle=True).item()
correct_outputs['DropoutLayer_fprop'][0][0][0]

array([ -0.        ,  -0.        ,   8.02934585, -10.3134877 ,
         1.6882652 ,  -0.        ,  -9.53079022,   0.        ,
         1.20283255,   0.        ,   0.        ,  -0.07837749,
        -0.        ,   0.        ,   0.61678661,   0.        ,
        -0.        ,  -6.72262231,  -0.        ,  -0.        ,
         0.61615918,  -3.07470604,  -0.        ,   0.85872071,
         4.00965053,  -0.42424617,   6.81615667,  -0.09082071,
        -5.15514679,   0.        ,  -0.        ,  -1.15213711,
         0.        ,  10.08008968,  -0.        ,   6.788294  ,
        -1.98825549,  -0.        ,  -1.59394607,  -0.        ,
         0.        ,  -0.12335789,  -9.77000395,   0.52317061,
         0.62916047, -11.6545745 ,   0.        ,  -0.        ,
         0.        ,   3.93763343,   6.18839754,  -0.83638025,
        -4.85869589,   3.54161168,   6.25257167,  -0.        ,
         0.        ,  10.0515509 ,   1.40540161,   0.        ,
         4.37313633,  -0.        ,   4.23127441,  -0.  

In [1]:
import numpy as np
n, p = 1, 0.1
rng = np.random.RandomState(92019)
s = np.random.binomial(1, 0.5, (3,64,64))
s.sum()

6102

In [2]:
import numpy as np
rng = np.random.RandomState(92019)
x = rng.normal(loc=0, scale=5.0, size=(50, 3, 64, 64))
np.sum(np.abs(x))


2447841.6697648065

In [3]:
(1,)+x[0].shape
    

(1, 3, 64, 64)

In [15]:
import numpy as np
data_dropout = np.array([
      [80.7, 0.549, 0.593],
      [83.0, 0.442, 0.502],
      [85.1, 0.329, 0.434],
      [85.4, 0.244, 0.457]
   ])
data_L1 = np.array([
    [79.5, 0.642, 0.658],
    [77.1, 0.744, 0.764],
    [2.41, 3.850, 3.850],
    [2.20, 3.850, 3.850]
])
data_L2 = np.array([
    [85.1, 0.306, 0.460],
    [84.9, 0.334, 0.450],
    [81.3, 0.586, 0.607],
    [39.2, 2.258, 2.256]
])
data_result = [data_dropout, data_L1, data_L2]
data_result[0][:,0]

array([80.7, 83. , 85.1, 85.4])