In [13]:
import numpy as np
a = {'acc' : (lambda y, t: (y.argmax(-1)==t.argmax(-1)).mean())(np.array([1,2,3]),np.array([1,2,5]))}
a


{'acc': 1.0}

In [10]:
b = np.array([1,2,55,4,7,4,3])
b.argmax()

2

In [3]:
params = dict(
learning_rate = 9e-4,
num_epochs = 100,
stats_interval = 1,
input_dim = 784, 
output_dim = 47,
hidden_dim = [32, 64, 128])
params['learning_rate']

0.0009

In [53]:
import numpy as np
input = np.arange(48).reshape(4,3,2,2)
print(input)
mask = ((np.random.rand(input.shape[1])>0.5)*1)[:,None,None]
print(mask)
input * mask


[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]

  [[ 8  9]
   [10 11]]]


 [[[12 13]
   [14 15]]

  [[16 17]
   [18 19]]

  [[20 21]
   [22 23]]]


 [[[24 25]
   [26 27]]

  [[28 29]
   [30 31]]

  [[32 33]
   [34 35]]]


 [[[36 37]
   [38 39]]

  [[40 41]
   [42 43]]

  [[44 45]
   [46 47]]]]
[[[0]]

 [[0]]

 [[1]]]


array([[[[ 0,  0],
         [ 0,  0]],

        [[ 0,  0],
         [ 0,  0]],

        [[ 8,  9],
         [10, 11]]],


       [[[ 0,  0],
         [ 0,  0]],

        [[ 0,  0],
         [ 0,  0]],

        [[20, 21],
         [22, 23]]],


       [[[ 0,  0],
         [ 0,  0]],

        [[ 0,  0],
         [ 0,  0]],

        [[32, 33],
         [34, 35]]],


       [[[ 0,  0],
         [ 0,  0]],

        [[ 0,  0],
         [ 0,  0]],

        [[44, 45],
         [46, 47]]]])

In [59]:
import os
correct_outputs = np.load(os.path.join(os.environ['MLP_DATA_DIR'], 'regularization_debug_pack.npy'), allow_pickle=True).item()
correct_outputs['DropoutLayer_fprop'].shape

(50, 3, 64, 64)